/work1/home/yenmr/tools/BSseeker2-master/bs_seeker2-call_methylation.py -x -i SRR13443687.bam -d /work1/home/yenmr/tools/BSseeker2-master/bs_utils/reference_genomes/tair10.fa_bowtie2/ &
/work1/home/yenmr/tools/BSseeker2-master/bs_seeker2-call_methylation.py -x -i SRR13443688.bam -d /work1/home/yenmr/tools/BSseeker2-master/bs_utils/reference_genomes/tair10.fa_bowtie2/ &
/work1/home/yenmr/tools/BSseeker2-master/bs_seeker2-call_methylation.py -x -i SRR1569252.bam -d /work1/home/yenmr/tools/BSseeker2-master/bs_utils/reference_genomes/tair10.fa_bowtie2/ &
/work1/home/yenmr/tools/BSseeker2-master/bs_seeker2-call_methylation.py -x -i SRR1569253.bam -d /work1/home/yenmr/tools/BSseeker2-master/bs_utils/reference_genomes/tair10.fa_bowtie2/ &
/work1/home/yenmr/tools/BSseeker2-master/bs_seeker2-call_methylation.py -x -i SRR24421255.bam -d /work1/home/yenmr/tools/BSseeker2-master/bs_utils/reference_genomes/tair10.fa_bowtie2/ &
/work1/home/yenmr/tools/BSseeker2-master/bs_seeker2-call_methylation.py -x -i SRR24421259.bam -d /work1/home/yenmr/tools/BSseeker2-master/bs_utils/reference_genomes/tair10.fa_bowtie2/ &
/work1/home/yenmr/tools/BSseeker2-master/bs_seeker2-call_methylation.py -x -i SRR24476325.bam -d /work1/home/yenmr/tools/BSseeker2-master/bs_utils/reference_genomes/tair10.fa_bowtie2/ &
/work1/home/yenmr/tools/BSseeker2-master/bs_seeker2-call_methylation.py -x -i SRR24476326.bam -d /work1/home/yenmr/tools/BSseeker2-master/bs_utils/reference_genomes/tair10.fa_bowtie2/ &
/work1/home/yenmr/tools/BSseeker2-master/bs_seeker2-call_methylation.py -x -i SRR5239972.bam -d /work1/home/yenmr/tools/BSseeker2-master/bs_utils/reference_genomes/tair10.fa_bowtie2/ &
/work1/home/yenmr/tools/BSseeker2-master/bs_seeker2-call_methylation.py -x -i SRR5239973.bam -d /work1/home/yenmr/tools/BSseeker2-master/bs_utils/reference_genomes/tair10.fa_bowtie2/ &
/work1/home/yenmr/tools/BSseeker2-master/bs_seeker2-call_methylation.py -x -i SRR5239984.bam -d /work1/home/yenmr/tools/BSseeker2-master/bs_utils/reference_genomes/tair10.fa_bowtie2/ &
/work1/home/yenmr/tools/BSseeker2-master/bs_seeker2-call_methylation.py -x -i SRR5239985.bam -d /work1/home/yenmr/tools/BSseeker2-master/bs_utils/reference_genomes/tair10.fa_bowtie2/ &
/work1/home/yenmr/tools/BSseeker2-master/bs_seeker2-call_methylation.py -x -i SRR5277784.bam -d /work1/home/yenmr/tools/BSseeker2-master/bs_utils/reference_genomes/tair10.fa_bowtie2/ &
/work1/home/yenmr/tools/BSseeker2-master/bs_seeker2-call_methylation.py -x -i SRR5277785.bam -d /work1/home/yenmr/tools/BSseeker2-master/bs_utils/reference_genomes/tair10.fa_bowtie2/ &
/work1/home/yenmr/tools/BSseeker2-master/bs_seeker2-call_methylation.py -x -i SRR5320832.bam -d /work1/home/yenmr/tools/BSseeker2-master/bs_utils/reference_genomes/tair10.fa_bowtie2/ &
/work1/home/yenmr/tools/BSseeker2-master/bs_seeker2-call_methylation.py -x -i SRR5320833.bam -d /work1/home/yenmr/tools/BSseeker2-master/bs_utils/reference_genomes/tair10.fa_bowtie2/ &
/work1/home/yenmr/tools/BSseeker2-master/bs_seeker2-call_methylation.py -x -i SRR6675996.bam -d /work1/home/yenmr/tools/BSseeker2-master/bs_utils/reference_genomes/tair10.fa_bowtie2/ &
/work1/home/yenmr/tools/BSseeker2-master/bs_seeker2-call_methylation.py -x -i SRR6675997.bam -d /work1/home/yenmr/tools/BSseeker2-master/bs_utils/reference_genomes/tair10.fa_bowtie2/ &
/work1/home/yenmr/tools/BSseeker2-master/bs_seeker2-call_methylation.py -x -i SRR7346214.bam -d /work1/home/yenmr/tools/BSseeker2-master/bs_utils/reference_genomes/tair10.fa_bowtie2/ &
/work1/home/yenmr/tools/BSseeker2-master/bs_seeker2-call_methylation.py -x -i SRR7346216.bam -d /work1/home/yenmr/tools/BSseeker2-master/bs_utils/reference_genomes/tair10.fa_bowtie2/ &
/work1/home/yenmr/tools/BSseeker2-master/bs_seeker2-call_methylation.py -x -i test.bam -d /work1/home/yenmr/tools/BSseeker2-master/bs_utils/reference_genomes/tair10.fa_bowtie2/ &
