bigWigAverageOverBed HDA6_1_sort_rmMtPt_150bp.bw ../tair10_TE_gene_expressed.bed HDA6_1_sort_rmMtPt_150bp.tab
bigWigAverageOverBed HDA6_4_sort_rmMtPt_150bp.bw ../tair10_TE_gene_expressed.bed HDA6_4_sort_rmMtPt_150bp.tab
bigWigAverageOverBed HL_2_sort_rmMtPt_150bp.bw ../tair10_TE_gene_expressed.bed HL_2_sort_rmMtPt_150bp.tab
bigWigAverageOverBed HL_3_sort_rmMtPt_150bp.bw ../tair10_TE_gene_expressed.bed HL_3_sort_rmMtPt_150bp.tab
bigWigAverageOverBed LDL_3_sort_rmMtPt_150bp.bw ../tair10_TE_gene_expressed.bed LDL_3_sort_rmMtPt_150bp.tab
bigWigAverageOverBed LDL_4_sort_rmMtPt_150bp.bw ../tair10_TE_gene_expressed.bed LDL_4_sort_rmMtPt_150bp.tab
bigWigAverageOverBed WT_2_sort_rmMtPt_150bp.bw ../tair10_TE_gene_expressed.bed WT_2_sort_rmMtPt_150bp.tab
bigWigAverageOverBed WT_3_sort_rmMtPt_150bp.bw ../tair10_TE_gene_expressed.bed WT_3_sort_rmMtPt_150bp.tab
