~/bin/bigWigAverageOverBed At-121.bam.CG.bw upTE_union_ID.bed WGBS_CG_121_upTE_union.tab
~/bin/bigWigAverageOverBed At-122.bam.CG.bw upTE_union_ID.bed WGBS_CG_122_upTE_union.tab
~/bin/bigWigAverageOverBed At-281.bam.CG.bw upTE_union_ID.bed WGBS_CG_281_upTE_union.tab
~/bin/bigWigAverageOverBed At-282.bam.CG.bw upTE_union_ID.bed WGBS_CG_282_upTE_union.tab
~/bin/bigWigAverageOverBed At-C1.bam.CG.bw upTE_union_ID.bed WGBS_CG_C1_upTE_union.tab
~/bin/bigWigAverageOverBed At-C2.bam.CG.bw upTE_union_ID.bed WGBS_CG_C2_upTE_union.tab
~/bin/bigWigAverageOverBed At-a1.bam.CG.bw upTE_union_ID.bed WGBS_CG_a1_upTE_union.tab
~/bin/bigWigAverageOverBed At-a121.bam.CG.bw upTE_union_ID.bed WGBS_CG_a121_upTE_union.tab
~/bin/bigWigAverageOverBed At-a122.bam.CG.bw upTE_union_ID.bed WGBS_CG_a122_upTE_union.tab
~/bin/bigWigAverageOverBed At-a2.bam.CG.bw upTE_union_ID.bed WGBS_CG_a2_upTE_union.tab
