~/bin/bigWigAverageOverBed At-121.bam.CHG.bw upTE_union_ID.bed WGBS_CHG_121_upTE_union.tab
~/bin/bigWigAverageOverBed At-122.bam.CHG.bw upTE_union_ID.bed WGBS_CHG_122_upTE_union.tab
~/bin/bigWigAverageOverBed At-281.bam.CHG.bw upTE_union_ID.bed WGBS_CHG_281_upTE_union.tab
~/bin/bigWigAverageOverBed At-282.bam.CHG.bw upTE_union_ID.bed WGBS_CHG_282_upTE_union.tab
~/bin/bigWigAverageOverBed At-C1.bam.CHG.bw upTE_union_ID.bed WGBS_CHG_C1_upTE_union.tab
~/bin/bigWigAverageOverBed At-C2.bam.CHG.bw upTE_union_ID.bed WGBS_CHG_C2_upTE_union.tab
~/bin/bigWigAverageOverBed At-a1.bam.CHG.bw upTE_union_ID.bed WGBS_CHG_a1_upTE_union.tab
~/bin/bigWigAverageOverBed At-a121.bam.CHG.bw upTE_union_ID.bed WGBS_CHG_a121_upTE_union.tab
~/bin/bigWigAverageOverBed At-a122.bam.CHG.bw upTE_union_ID.bed WGBS_CHG_a122_upTE_union.tab
~/bin/bigWigAverageOverBed At-a2.bam.CHG.bw upTE_union_ID.bed WGBS_CHG_a2_upTE_union.tab
