~/bin/bigWigAverageOverBed At-121.bam.CHH.bw upTE_union_ID.bed WGBS_CHH_121_upTE_union.tab
~/bin/bigWigAverageOverBed At-122.bam.CHH.bw upTE_union_ID.bed WGBS_CHH_122_upTE_union.tab
~/bin/bigWigAverageOverBed At-281.bam.CHH.bw upTE_union_ID.bed WGBS_CHH_281_upTE_union.tab
~/bin/bigWigAverageOverBed At-282.bam.CHH.bw upTE_union_ID.bed WGBS_CHH_282_upTE_union.tab
~/bin/bigWigAverageOverBed At-C1.bam.CHH.bw upTE_union_ID.bed WGBS_CHH_C1_upTE_union.tab
~/bin/bigWigAverageOverBed At-C2.bam.CHH.bw upTE_union_ID.bed WGBS_CHH_C2_upTE_union.tab
~/bin/bigWigAverageOverBed At-a1.bam.CHH.bw upTE_union_ID.bed WGBS_CHH_a1_upTE_union.tab
~/bin/bigWigAverageOverBed At-a121.bam.CHH.bw upTE_union_ID.bed WGBS_CHH_a121_upTE_union.tab
~/bin/bigWigAverageOverBed At-a122.bam.CHH.bw upTE_union_ID.bed WGBS_CHH_a122_upTE_union.tab
~/bin/bigWigAverageOverBed At-a2.bam.CHH.bw upTE_union_ID.bed WGBS_CHH_a2_upTE_union.tab
