bamCoverage -b ChIP_H3Ac_WT_1.bam -o ChIP_H3Ac_WT_1.bw --normalizeUsing RPKM --binSize 10
bamCoverage -b ChIP_H3Ac_WT_2.bam -o ChIP_H3Ac_WT_2.bw --normalizeUsing RPKM --binSize 10
bamCoverage -b ChIP_H3Ac_hda6_1.bam -o ChIP_H3Ac_hda6_1.bw --normalizeUsing RPKM --binSize 10
bamCoverage -b ChIP_H3Ac_hda6_2.bam -o ChIP_H3Ac_hda6_2.bw --normalizeUsing RPKM --binSize 10
bamCoverage -b ChIP_H3Ac_hda6ldl12_1.bam -o ChIP_H3Ac_hda6ldl12_1.bw --normalizeUsing RPKM --binSize 10
bamCoverage -b ChIP_H3Ac_hda6ldl12_2.bam -o ChIP_H3Ac_hda6ldl12_2.bw --normalizeUsing RPKM --binSize 10
bamCoverage -b ChIP_H3Ac_ldl12_1.bam -o ChIP_H3Ac_ldl12_1.bw --normalizeUsing RPKM --binSize 10
bamCoverage -b ChIP_H3Ac_ldl12_2.bam -o ChIP_H3Ac_ldl12_2.bw --normalizeUsing RPKM --binSize 10
bamCoverage -b ChIP_H3K4me2_WT_1.bam -o ChIP_H3K4me2_WT_1.bw --normalizeUsing RPKM --binSize 10
bamCoverage -b ChIP_H3K4me2_WT_2.bam -o ChIP_H3K4me2_WT_2.bw --normalizeUsing RPKM --binSize 10
bamCoverage -b ChIP_H3K4me2_hda6_1.bam -o ChIP_H3K4me2_hda6_1.bw --normalizeUsing RPKM --binSize 10
bamCoverage -b ChIP_H3K4me2_hda6_2.bam -o ChIP_H3K4me2_hda6_2.bw --normalizeUsing RPKM --binSize 10
bamCoverage -b ChIP_H3K4me2_hda6ldl12_1.bam -o ChIP_H3K4me2_hda6ldl12_1.bw --normalizeUsing RPKM --binSize 10
bamCoverage -b ChIP_H3K4me2_hda6ldl12_2.bam -o ChIP_H3K4me2_hda6ldl12_2.bw --normalizeUsing RPKM --binSize 10
bamCoverage -b ChIP_H3K4me2_ldl12_1.bam -o ChIP_H3K4me2_ldl12_1.bw --normalizeUsing RPKM --binSize 10
bamCoverage -b ChIP_H3K4me2_ldl12_2.bam -o ChIP_H3K4me2_ldl12_2.bw --normalizeUsing RPKM --binSize 10
bamCoverage -b ChIP_hda6_1.bam -o ChIP_hda6_1.bw --normalizeUsing RPKM --binSize 10
bamCoverage -b ChIP_hda6_2.bam -o ChIP_hda6_2.bw --normalizeUsing RPKM --binSize 10
bamCoverage -b ChIP_hda6_input.bam -o ChIP_hda6_input.bw --normalizeUsing RPKM --binSize 10
bamCoverage -b ChIP_ldl1_1.bam -o ChIP_ldl1_1.bw --normalizeUsing RPKM --binSize 10
bamCoverage -b ChIP_ldl1_2.bam -o ChIP_ldl1_2.bw --normalizeUsing RPKM --binSize 10
bamCoverage -b ChIP_ldl1_input.bam -o ChIP_ldl1_input.bw --normalizeUsing RPKM --binSize 10
